// ReSharper disable AutoPropertyCanBeMadeGetOnly.Global
namespace AspNetWebpack.AssetHelpers
{
    /// <summary>
    /// Webpack options configured in appsettings.
    /// </summary>
    public class WebpackOptions
    {
        /// <summary>
        /// Gets or sets the public url for the dev server. This needs to be accessible from the client.
        /// </summary>
        public string? PublicDevServer { get; set; }

        /// <summary>
        /// Gets or sets the internal url for the dev server. This needs to be accessible from the server.
        /// </summary>
        public string? InternalDevServer { get; set; }

        /// <summary>
        /// Gets or sets name of the manifest file generated by Webpack.
        /// </summary>
        public string ManifestFile { get; set; } = "manifest.json";

        /// <summary>
        /// Gets or sets the public path set in Webpack.
        /// </summary>
        public string AssetsPublicPath { get; set; } = "/dist/";
    }
}
